parameters:
- name: DotNetFinalVersionKind
  type: string
  displayName: .NET Final Version Kind
  values:
  - prerelease
  - release
  default: prerelease

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/main
    - internal/release/*

variables:
- name: LinuxImage
  value: 1es-ubuntu-2204
- name: WindowsImage
  value: 1es-windows-2022
- template: /eng/pipelines/common-variables.yml@self
- template: /eng/common/templates-official/variables/pool-providers.yml@self

- ${{ if eq(variables['_RunAsPublic'], 'true') }}:
  - name: _AdditionalBuildArgs
    value: ''
  - name: _BuildJobDisplayName
    value: 'Build and Test'
  - name: _DotNetFinalVersionKind
    value: ''
- ${{ else }}:
  - name: _AdditionalBuildArgs
    value: '/p:Test=false'
  - name: _BuildJobDisplayName
    value: 'Build, Sign and Publish'
  - name: _DotNetFinalVersionKind
    value: /p:DotNetFinalVersionKind=${{ parameters.DotNetFinalVersionKind }}

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    featureFlags:
      autoBaseline: true
    sdl:
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      policheck:
        enabled: true
      tsa:
        enabled: true
    pool:
      name: $(DncEngInternalBuildPool)
      image: $(WindowsImage)
      os: windows
    containers:
      LinuxContainer:
        image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-fpm
    stages:
    - stage: build
      displayName: CI
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          artifacts:
            publish:
              artifacts: false
              logs: true
              manifests: true
          enableMicrobuild: true
          enablePublishUsingPipelines: true
          publishAssetsImmediately: true
          enableSourceIndex: ${{ and(eq(variables._RunAsInternal, True), eq(variables['Build.SourceBranch'], 'refs/heads/internal/main')) }}
          workspace:
            clean: all
          jobs:
          - job: build_and_pack_windows
            displayName: 'Build and pack Windows'
            timeoutInMinutes: 60
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(WindowsImage)
              os: windows
            preSteps:
            - checkout: self
              fetchDepth: 0
              clean: true
            steps:
            # Manually run an Azure DevOps job with the variable 'DotNetFinalVersionKind' set to 'release' to
            # generate a stable version (package names without preview suffix strings).
            # For nightly builds this value should be empty (default value).
            # https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#package-versioning
            - script: eng\common\cibuild.cmd
                -configuration Release
                -prepareMachine
                /p:Test=false
                $(_DotNetFinalVersionKind)
                $(_AdditionalBuildArgs)
                $(_InternalBuildArgs)
              displayName: $(_BuildJobDisplayName)

    - ${{ if eq(variables._RunAsInternal, True) }}:
      - template: /eng/common/templates-official/post-build/post-build.yml@self
        parameters:
          publishAssetsImmediately: true
