<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetCurrent)-unix;$(NetCurrent)-windows</TargetFrameworks>
    <IsTestUtilityProject>true</IsTestUtilityProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\src\System.Data.SqlClient.csproj" />
  </ItemGroup>

</Project>
